<?php
/**
 * @author    Nickolay Mavrin <mavrinnick@gmail.com>
 * @copyright Copyright (c) 2023
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Omnipay\NetworkGenius\Message\Request;

use Omnipay\NetworkGenius\Message\Response\AbstractResponse;
use Omnipay\NetworkGenius\Message\Response\CompletePurchaseResponse;

class CompletePurchaseRequest extends AbstractRequest
{
    /**
     * @return array
     */
    protected function getHeaders(): array
    {
        return [
            "Authorization" => sprintf("Bearer %s", $this->getParameter('authToken')),
        ];
    }

    /**
     * @return array
     *
     */
    public function getData(): array
    {
        return [];
    }

    /**
     * @return string
     */
    public function getHttpMethod(): string
    {
        return 'GET'; // TODO: Change the autogenerated stub
    }


    /**
     * @inheritDoc
     */
    protected function getMethod($reference = null): string
    {
        return sprintf('transactions/outlets/%s/orders/%s', $this->getParameter('reference'), $this->getTransactionReference());
    }

    /**
     * @inheritDoc
     */
    protected function createResponse(AbstractRequest $request, $content): AbstractResponse
    {
        return new CompletePurchaseResponse($request, $content);
    }
}
